### ISSUE TITLE
README needs an extra "note" about needing apache2 pre-installed

### ISSUE THREAD

**Issue by bmullan** [lcherone/Deval#2]
In the README it has this section:

> Once done, install the project:
> 
> \# yes do it 
> **rm /var/www/html -Rf && mkdir /var/www/html**
> \#
> cd /var/www/html
> 
> composer create-project lcherone/deval .
> 

Since this is a new install Ubuntu "server" there is no /var/www directory yet?  So the section in bold above will fail.   Installing apache2 before executing the above... works.

**Comment by lcherone** [comment]
Facepalm, your right, fixed it.. yeah clean as a whistle is required so if apache is installed nginx will fail, ive updated the readme with a new process.

Thanks for reporting it.
