### ISSUE TITLE
README - perhaps a bug? 

### ISSUE THREAD

**Issue by bmullan** [lcherone/Deval#3]
> Once done, install the project:
> 
> \# yes do it 
> rm /var/www/html -Rf && mkdir /var/www/html
> 
> \#
> cd /var/www/html
> 
> **composer create-project lcherone/deval .**

When I executed "composer create-project lcherone/deval ." as a sudo user I got a red box with a message that  said don't execute as superuser

But when I executed as my normal user ID it too failed with permissions errors.

So I re-executed ...

**$ sudo composer create-project lcherone/deval .**

I still got that red box warning message but I waited in in about 10 seconds it started installing ok??

**Comment by lcherone** [comment]
Thanks for reporting it.

With this project we need root user for the post project install script, I've updated the readme to reflect it.
