### ISSUE TITLE
Admin panel doesn't loading after rebooting.

### ISSUE THREAD

**Issue by talyguryn** [lcherone/Deval#6]
I tried to run this panel on a new server. After system reloading I see loader on white screen and nothing more. No errors in log file.

**Comment by lcherone** [comment]
Do you mean going to `http://IP:88` the browser is white screen?

What browser are you using and what version?

I did test it in chrome, opera, edge and firefox. Plus I've added babel-polyfill, so it should work.

Is the browser developer tools console showing anything?

**Comment by talyguryn** [comment]
**Solution**: emptying cache has helped. But it is not obvious 😬

> Do you mean going to http://IP:88 the browser is white screen?
Yes

> Is the browser developer tools console showing anything?
Safari 11.1. Console is empty. Panel worked fine before rebooting.

**Comment by lcherone** [comment]
Cool glad you sorted it, didn't test Safari.. as its using nuxt.js, I think browser support would be pretty good.
